[package]
name = "simulation-wasm"
version = "0.1.0"
description = "A sample project with wasm-pack"
license = "MIT/Apache-2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
rand = "0.8.4"
wasm-bindgen = "0.2"
queues = "1.1.0"
serde_json = "1.0.72"
console_error_panic_hook = "0.1.7"
num-traits = "0.2.14"
num-derive = "0.3.3"
serde_derive = "1.0.131"
serde = { version = "1.0", features = ["derive"] }